package table

import "github.com/nboughton/go-roll"

// Scrap table
var Scrap = roll.List{
	Items: []string{
		"Action figure (He-Man)",
		"Comic book, very violent",
		"Alarm clock, mechanical",
		"Concrete mixer, rusty",
		"Aquarium, no fish",
		"Cooking pot",
		"Barbie doll",
		"Credit card",
		"Baseball bat (page 86)",
		"Crime novel",
		"Basket ball, flat",
		"Cutlery, D6 pieces",
		"Beard trimmer",
		"Cylinder hat",
		"Beret, red",
		"Dala horse",
		"Bible",
		"Deodorant bottle",
		"Bicycle chain (page 86)",
		"Desk lamp",
		"Bicycle frame, no wheels",
		"Detergent, bottle",
		"Bicycle pump",
		"Dice, D6",
		"Binder, full of financial records",
		"Diving snorkel",
		"Boots (Gear Bonus +1 when hiking)",
		"Doll",
		"Bouncing ball",
		"Downhill ski (only one)",
		"Box of cereal, unopened",
		"Dress shoes, worn down",
		"Box of chocolates (still edible, D6 rations of grub)",
		"Dumbbell, 10 lb",
		"Boxing glove",
		"Easel, for painting",
		"Briefcase",
		"Eating knife (scrap knife)",
		"Bullhorn (broken)",
		"Electric guitar, broken",
		"Can opener",
		"Electric mixer",
		"Candelabra",
		"Electric shaver",
		"Car tire",
		"Electric toothbrush",
		"Carving knife",
		"Empty frame",
		"Cash register",
		"Extension cord",
		"Cat 5 cable, 2D6 feet long",
		"Face mask, Donald Duck",
		"Ceiling fan",
		"Face mask, skeleton",
		"Champagne glasses, D6",
		"Facemask, Santa Claus",
		"Chandelier",
		"Fake fangs",
		"Charcoal grill",
		"False teeth",
		"Children’s drawing",
		"Fantasy novel, very thick",
		"Cigarettes, half-empty pack",
		"Fire extinguisher",
		"Clothes hanger",
		"Fireworks, D6, still functional",
		"Coffee cup with print",
		"Flashlight, broken",
		"Coffee table",
		"Floor lamp",
		"Coloring book for kids (half done)",
		"Flute, plastic",
		"Comb",
		"Folding chair",
		"Football",
		"Mascara",
		"Fork",
		"Mathematics book",
		"Frying pan (blunt instrument)",
		"Microwave oven (broken)",
		"Gaffer tape",
		"Mirror",
		"Glass pearls",
		"Movie DVDs, D6",
		"Golf club (blunt instrument)",
		"Movie poster",
		"Grass seeds in small bag",
		"Music CDs, D6",
		"Hair dryer",
		"National flag, torn",
		"Hair gel",
		"Necktie",
		"Headphones, with microphone",
		"Nicotine chewing gum",
		"Hedge trimmer (scrap knife)",
		"Oriental carpet",
		"Herbal salt",
		"Pacifier",
		"Hockey club (blunt instrument)",
		"Pack of tube socks",
		"Hot dog cart",
		"Paper handkerchiefs, D666",
		"Hubcap, Volvo",
		"Pepper mill",
		"IKEA chair",
		"Photo album",
		"Infant formula (gives D6 rations of grub)",
		"Photo of happy family",
		"Instant coffee",
		"Picture of a cat",
		"Instant noodles (D6 rations of grub)",
		"Piggy bank (empty)",
		"Iron pipe (blunt instrument)",
		"Plastic bags, D66",
		"Jack",
		"Plastic bottle, empty",
		"Jeans, stonewashed",
		"Plastic dinosaur",
		"Jigsaw puzzle",
		"Plastic flowers, D6",
		"Jumpsuit, cloth",
		"Plastic skeleton model",
		"Key ring, 2D6 keys",
		"Plastic straws, pack of 100",
		"Keyboard, missing a few keys",
		"Playing cards",
		"Ladder, rusty (Gear Bonus +1 when climbing)",
		"Popcorn, unopened bag",
		"Ladies boots",
		"Princess dress, for kids",
		"Ladies hat",
		"Prize medal",
		"Laptop computer, broken",
		"Quilted jacket (Gear Bonus +1 against cold)",
		"Lawn mower",
		"Rabbit suit, adult size",
		"Light bulbs, D6",
		"Recliner",
		"Lipstick",
		"Remote control",
		"Liquid soap",
		"Roller skates",
		"Loudspeaker (broken)",
		"Rubber boot",
		"Love letter, yellowed",
		"Rubber duck",
		"Magnifying glass",
		"Saxophone",
		"Scarf, colorful (Gear Bonus +1 against cold)",
		"Toy car",
		"Scientific dissertation",
		"Toy pirates",
		"Scuba mask",
		"Toy sword",
		"Scuba suit, worn out",
		"Toy tractor",
		"Sex toy",
		"Toy train set",
		"Shopping cart",
		"Traffic cones, D6",
		"Skateboard",
		"Trombone",
		"Sketch book, full of sketches",
		"TV set, broken",
		"Ski boot",
		"Ski hat (Gear Bonus +1 against cold)",
		"Twinkies, D6 (still edible, each is a ration of grub)",
		"Skin lotion, bottle",
		"Typewriter",
		"Sleeping pad",
		"Umbrella, broken",
		"Snowglobe",
		"Underwear",
		"Sofa, broken",
		"Vacuum cleaner",
		"Spider-Man suit for kids",
		"Vacuum flask",
		"Sports bottle",
		"Vase",
		"Sports jersey",
		"VHS cassette",
		"Sports prize cup",
		"Video game console",
		"Stapler",
		"Vinyl record, well played",
		"Starburst candy (one ration of grub)",
		"Walking frame",
		"Stroller",
		"Walkman with headphones and cassette",
		"Surf board",
		"Wall clock",
		"Suspenders",
		"Wallet full of moldy cash",
		"Swimming goggles",
		"Water pistol",
		"Synthesizer",
		"Welding mask",
		"T-shirt with text “Heisenberg”",
		"Whiskey bottle (empty)",
		"Tabletop globe",
		"Whiteboard marker",
		"Teddy bear",
		"Wig, blonde",
		"Telephone",
		"Wine bottle, undrinkable (1 Rot Point)",
		"Tennis ball",
		"Wok",
		"Thermometer, broken",
		"Wrecking bar",
		"Tire iron",
		"Wristwatch, broken",
		"Toilet brush",
		"Yellowed copy of the Mutant Chronicles RPG",
		"Toothbrush",
		"Yo-yo (blunt instrument)",
		"Towel marked 'Sheraton'",
	},
}
